name: "SamX Genomics"
description: "This is the web page for the Sampath Perumal."

url: "http://samxgenomics.github.io"

paginate: 5
paginate_path: "news/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
